name: agent_q
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^3.17.0
  flutter_fireworks: ^1.0.8
  game_levels_scrolling_map: ^0.0.7
  games_services: ^5.0.0
  shared_preferences: ^2.2.3
  flame_splash_screen: ^0.3.1+2
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/images/achievements_and_progression/
    - assets/images/background_images/
    - assets/images/background_images/zombie_worlds/
    - assets/images/background_images/deep_facility_world/
    - assets/images/characters/
    - assets/images/hud_and_ui_elements/
    - assets/images/pickups_and_powerups/
    - assets/audio/


